name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          # Humne 'python_version' wali line hata di hai
          command: buildozer android debug
          buildozer_version: stable
